services:
  load-balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_HOST: database
      DB_USER: ${DB_USER}
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_DATABASE: ${DB_DATABASE}
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SERVICE_DISCOVERY_HOST: service-discovery:2181
      TEST_USERNAME: ${TEST_USERNAME}
      TEST_PASSWORD: ${TEST_PASSWORD}
      TEST_EMAIL: ${TEST_EMAIL}
    secrets:
      - db_password
      - jwt_secret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      database:
        condition: service_healthy
      service-discovery:
        condition: service_started

  chat-server:
    build:
      context: ./chat-server
      dockerfile: Dockerfile
    environment:
      KV_STORE_HOST: kv-store
      NODE_ENV: ${NODE_ENV}
      PORT: 80
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      SERVICE_DISCOVERY_HOST: service-discovery:2181
      SERVER_ID: "chat"

    deploy:
      mode: replicated
      replicas: 2
    secrets:
      - jwt_secret
    depends_on:
      kv-store:
        condition: service_healthy
      service-discovery:
        condition: service_started

  presence-server:
    build:
      context: ./presence-server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 80
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      SERVICE_DISCOVERY_HOST: service-discovery:2181
      SERVER_ID: "presence"
    deploy:
      mode: replicated
      replicas: 2
    secrets:
      - jwt_secret
    depends_on:
      kv-store:
        condition: service_healthy
      service-discovery:
        condition: service_started

  database:
    image: mysql:8.3
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "3306:3306"
    secrets:
       - db_root_password
       - db_password
    healthcheck:
      test: ["CMD-SHELL", "exit | mysql -h localhost -P 3306 -u $$MYSQL_USER -p$$(cat $$MYSQL_ROOT_PASSWORD_FILE)" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - mysql-data:/var/lib/mysql

  kv-store:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=chat_cluster
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "SELECT now() FROM system.local;"]
      interval: 15s
      timeout: 5s
      retries: 10

  service-discovery:
    image: zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper:2888:3888;2181
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt

volumes:
  cassandra-data:
  mysql-data:
  zookeeper-data:
  zookeeper-datalog:
